// YoDips /app/ bootstrap (Compose-wasm PWA). External file — loaded as a
// classic <script src="loader.js"> from index.html <head> so the /app/* CSP
// (web/vercel.json) can drop script-src 'unsafe-inline' while still running
// code before composeApp.js is parsed.
//
// Responsibility split vs index.html <style>:
//   - index.html <style> carries the static #loader/#ComposeTarget CSS.
//   - loader.js applies the dark mode (html.theme-dark) BEFORE first paint so
//     the PWA never flashes a white screen for dark-mode users (FOUC guard,
//     parity with the SPA `/` guard).
//
// This file is copied verbatim into the Gradle wasm dist by the Kotlin
// resources pipeline (wasmJsMain/resources), then copied to /app/ by
// web/scripts/build-pwa-app.mjs together with composeApp.js. Keep it free of
// any inline event handlers and free of backticks/template literals.

(function () {
  'use strict';

  // ---- FOUC guard: theme before first paint (mirror of the SPA guard) ----
  // The wasm theme store key is 'yodips_theme' (Main.kt ThemeController).
  // Default = system preference. Applies html.theme-dark on <html> — the CSS
  // in index.html keys off it.
  var applyTheme = function () {
    var stored = null;
    try {
      stored = window.localStorage.getItem('yodips_theme');
    } catch (e) {
      stored = null;
    }
    var dark = stored ? stored === 'dark' : !!(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (dark) document.documentElement.classList.add('theme-dark');
    else document.documentElement.classList.remove('theme-dark');
    return dark;
  };
  applyTheme();

  // Keep <meta name="theme-color"> in sync (Chrome UI color on mobile).
  var syncMetaThemeColor = function (dark) {
    var meta = document.querySelector('meta[name="theme-color"]:not([media])');
    if (meta) meta.setAttribute('content', dark ? '#121212' : '#01637E');
  };
  try {
    syncMetaThemeColor(applyTheme());
  } catch (e) { /* non-critical */ }

  // ---- Loader hide: once the Compose runtime is drawing (fonts ready), hide
  // the #loader overlay; 20s hard fallback so a stalled load never traps the
  // user on the loading screen. ----
  var hideLoader = function () {
    var l = document.getElementById('loader');
    if (l) l.classList.add('hidden');
  };
  if (document.fonts && document.fonts.ready) document.fonts.ready.then(hideLoader);
  setTimeout(hideLoader, 20000);

  // ---- Uppercase pairing/token inputs: Compose-wasm types into a hidden
  // <input> that does NOT forward KeyboardCapitalization to the IME, so force
  // autocapitalize at the DOM level right before the keyboard shows. ----
  document.addEventListener(
    'focusin',
    function (e) {
      var el = e && e.target;
      if (!el) return;
      var tag = el.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA') {
        el.setAttribute('autocapitalize', 'characters');
        el.setAttribute('autocorrect', 'off');
        el.setAttribute('spellcheck', 'false');
      }
    },
    true,
  );

  // ---- PWA: register the service worker only when served under /app/ in
  // production (sw.js is generated by web/scripts/build-pwa-app.mjs; the dev
  // webpack :8080 server has none). ----
  if ('serviceWorker' in navigator && location.pathname.indexOf('/app/') === 0) {
    navigator.serviceWorker.register('sw.js').catch(function () {
      /* offline is not a hard requirement */
    });
  }
})();
