// Policy test for the non-blocking generated-Kotlin-wasm-lock advisory step in
// .github/workflows/ci.yaml (security-scan job).
//
// Guards the YD-CI-001 disposition: mobile/kotlin-js-store/wasm/yarn.lock (+
// mobile/build/wasm/yarn.lock) are autogenerated by the Kotlin Gradle plugin's
// Yarn wrapper and pin ws@8.18.0/8.20.1 (HIGH memory-exhaustion advisory,
// fixed >= 8.21.0). The lock is NEVER hand-edited; the upgrade is deferred to a
// Kotlin toolchain bump. The CI step is ADVISORY: it warns and exits 0 until a
// regenerated lock satisfies ws >= 8.21.0.
//
// This test proves the advisory is VISIBLE, not silent:
//   1. the step exists in security-scan after the npm audit (extension) step;
//   2. an expected lock file that is MISSING produces an explicit WARN line
//      (the `if [ ! -f "$lock" ]` branch) rather than being skipped silently;
//   3. a lock still pinning ws < 8.21.0 produces a WARN line;
//   4. both branches terminate with `exit 0` (non-blocking by design);
//   5. the step is scoped ONLY to the two accepted generated locks (no other
//      path is warned about).
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ciYaml = readFileSync(
  resolve(here, "..", "..", ".github", "workflows", "ci.yaml"),
  "utf8",
);

function advisoryStepText() {
  const lines = ciYaml.split("\n");
  const stepStart = lines.findIndex((l) =>
    l.includes("advisory — generated Kotlin wasm lock ws version (non-blocking)"),
  );
  assert.ok(stepStart >= 0, "ci.yaml must contain the wasm-lock advisory step");
  // Step block ends at the next line whose indent is <= the step marker (6).
  let end = lines.length;
  for (let i = stepStart + 1; i < lines.length; i++) {
    const l = lines[i];
    if (l.trim().length === 0) continue;
    const indent = l.length - l.trimStart().length;
    if (indent <= 6) { end = i; break; }
  }
  return lines.slice(stepStart, end).join("\n");
}

describe("ci.yaml Kotlin wasm lock advisory (non-blocking, visible)", () => {
  it("advisory step exists after the npm audit (extension) step in security-scan", () => {
    const scanJob = ciYaml.slice(
      ciYaml.indexOf("  security-scan:"),
      ciYaml.indexOf("  test:"),
    );
    const auditIdx = scanJob.indexOf("npm audit (extension)");
    const advisoryIdx = scanJob.indexOf("advisory — generated Kotlin wasm lock");
    assert.ok(auditIdx >= 0, "security-scan must contain npm audit (extension)");
    assert.ok(
      advisoryIdx > auditIdx,
      "advisory step must come after the npm audit (extension) step",
    );
  });

  it("scoped only to the two accepted generated locks", () => {
    const step = advisoryStepText();
    for (const lock of [
      "mobile/kotlin-js-store/wasm/yarn.lock",
      "mobile/build/wasm/yarn.lock",
    ]) {
      assert.ok(step.includes(lock), `step must reference ${lock}`);
    }
    // No other lock path may be warned about. Match full path tokens (starting
    // with mobile/) so prose mentions like "generated Kotlin wasm yarn.lock"
    // or the filename alone are not mistaken for a warned path.
    const refs = step.match(/mobile\/[a-zA-Z0-9_./-]+\.lock/g) ?? [];
    for (const r of refs) {
      assert.ok(
        r === "mobile/kotlin-js-store/wasm/yarn.lock" || r === "mobile/build/wasm/yarn.lock",
        `advisory must be scoped to the generated wasm locks only, found: ${r}`,
      );
    }
  });

  it("missing-file branch emits an explicit WARN (visible, not silent)", () => {
    const step = advisoryStepText();
    assert.match(
      step,
      /if \[ ! -f "\$lock" \]; then[\s\S]*WARN\(advisory\): \$lock MISSING/,
      "a missing expected lock must produce an explicit WARN(advisory): ... MISSING line",
    );
    // The old silent skip (`[ -f "$lock" ] || continue`) must be gone.
    assert.doesNotMatch(
      step,
      /\[ -f "\$lock" \] \|\| continue/,
      "missing locks must not be silently skipped",
    );
  });

  it("outdated ws version emits a WARN line", () => {
    const step = advisoryStepText();
    assert.match(
      step,
      /\*\) echo "WARN\(advisory\): \$lock ws \$ver — upgrade to >= 8\.21\.0/,
      "a lock pinning ws < 8.21.0 must warn with the upgrade note",
    );
  });

  it("stays non-blocking: both branches end in exit 0", () => {
    const step = advisoryStepText();
    assert.match(step, /set \+e/, "must not be fail-fast");
    // The terminal line of the run block is `exit 0` regardless of found=1.
    const runBlock = step.slice(step.indexOf("run: |"));
    const lines = runBlock.split("\n").filter((l) => l.trim().length > 0);
    assert.equal(
      lines[lines.length - 1].trim(),
      "exit 0",
      "advisory must terminate exit 0 (non-blocking)",
    );
    // Every branch path leads to exit 0: there is no `exit 1` anywhere.
    assert.doesNotMatch(runBlock, /exit 1/, "advisory must never exit 1");
  });
});
